name: iOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.2.1'
      - name: Install Dependencies
        run: |
          sudo gem install cocoapods
          pod install
      - name: Build
        run: xcodebuild -workspace LocketUploader.xcworkspace -scheme LocketUploader -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' build
